apiVersion: 1
datasources:
  - name: MySQL
    type: mysql
    url: bxa3nz7gedsjlro8pmnx-mysql.services.clever-cloud.com:3306
    database: bxa3nz7gedsjlro8pmnx
    user: uiurmwccxfzoehb1
    secureJsonData:
      password: GNJAwVKNTUbAwurZxTjJ
    editable: true